### ISSUE TITLE
Add warns

### ISSUE THREAD

**Issue by CometWhoosh** [white-van/WVAnonBot#40]
### What problem are you facing?

Currently, admins and mods can't warn users if they are behaving inappropriately, so the only act of moderation possible is bans.

### What can we do to fix that problem?

Introduce a warn command that allows admins and mods to warn users anonymously through the bot. The warn should consist of an optional reason as well as the number of the message that elicited the warn.

The following features should be included:

**Warn command**
A warn command of the form `!anon warn {msg id} {reason (optional)}` should be implemented. After warning a user, the bot should DM the user with the warn and reply to the warn command with a confirmation that it has been sent. The confirmation should mention how many warns the user now has.

**Warnlist**
There should be a warnlist command of the form `!anon warnlist {anon id (optional)}`. If no anon id is provided, then the command should print out a list of all warnings that currently exist against all users of the bot in an embed. Each user in the list should be identified by their anon id, and all of their warnings should be listed. For each warning, the message id, reason, and date should be shown. If an anon id is provided, then only the warnings for that user should be printed out.

**Comment by jcserv** [comment]
Worth considering that there is a potential privacy risk that could be "socially determined" here.
If a user has multiple warns, those messages could be used to piece together the identity of the user.

This issue already exists for sending messages in general so I don't think it's a big deal but definitely something to keep in mind.

**Comment by CometWhoosh** [comment]
That's a good point! One possible alternative to the approach described in the issue is if we don't have a warn list, but instead just automatically temp ban someone once they reach a set amount of warns. That way, we can't track the warns of each user, but we would still temp ban someone if they continue to act in an undesirable manner.

**Comment by jcserv** [comment]
I like that much more! Great idea

**Comment by CometWhoosh** [comment]
Sounds good! One thing to note—I think that warns should expire after a set amount of time. It would be unfair if a user was temp banned for warns that were issued a very long time apart from each other.
