### ISSUE TITLE
Display suicide prevention resources after detecting possibly suicidal messages

### ISSUE THREAD

**Issue by CometWhoosh** [white-van/WVAnonBot#51]
### What problem are you facing?

Since many people use the bot for venting about mental health issues, occasionally someone will send a message that is possibly suicidal. 

### What can we do to fix that problem?

When a user sends a message, we can search for any words related to suicide, and if any appear, we can respond with a message that lists suicide prevention resources.

**Comment by Multivalence** [comment]
We could use NLP to accomplish this. There is a repository that gathers data sets from subreddits where suicidal comments are common and detects if other comments are suicidal. https://github.com/hesamuel/goodbye_world.

**Comment by CometWhoosh** [comment]
Ooh thanks for linking that! Yeah I agree, we should use that repo and test it out to see how well it performs.

**Comment by Multivalence** [comment]
Yeah. Since it's written in Python, I think it would be easier to create a stand-alone REST API using a library like Flask. The bot sends a request to it with a message payload and it returns how likely it is to be suicidal.

**Comment by CometWhoosh** [comment]
This will be unnecessary once issue #56 is implemented
